version: "3.1"

services:
  alarmy-globproxy:
    container_name: alarmy-globproxy
    image: alarmy-globproxy:latest
    build: ./globproxy
    ports:
      - 8082:8082
    networks:
      - docker-network

  alarmy-web:
    container_name: alarmy-web
    image: alarmy-web:latest
    build: ./web
    ports:
      - "80:80"
      - "443:443"
    # volumes:
    #   - ./production.conf:/etc/nginx/conf.d/default.conf
    #   - /docker-volumes/etc/letsencrypt/live/shorty.codes/fullchain.pem:/etc/letsencrypt/live/shorty.codes/fullchain.pem
    #   - /docker-volumes/etc/letsencrypt/live/shorty.codes/privkey.pem:/etc/letsencrypt/live/shorty.codes/privkey.pem
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
