version: '3.1'

services:

  production-nginx-container:
    container_name: 'production-nginx-container'
    image: alarmy-web:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./production.conf:/etc/nginx/conf.d/default.conf
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/shorty.codes/fullchain.pem:/etc/letsencrypt/live/shorty.codes/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/shorty.codes/privkey.pem:/etc/letsencrypt/live/shorty.codes/privkey.pem
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge